/**
 * Supabase Schema Phase 11 验证：drafts 表
 */

import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const migrationPath = join(
  __dirname,
  '../../../../../supabase/migrations/20260221200000_phase11_drafts.sql'
)

describe('Supabase migration Phase 11: drafts table', () => {
  let migration: string

  beforeAll(() => {
    migration = readFileSync(migrationPath, 'utf-8')
  })

  it('should create drafts table', () => {
    expect(migration).toMatch(/CREATE TABLE IF NOT EXISTS drafts/)
  })

  it('should use TEXT primary key (server-generated draft_ prefix ID)', () => {
    // Design: id is TEXT generated by server with 'draft_' prefix
    expect(migration).toMatch(/id\s+TEXT PRIMARY KEY/)
  })

  it('should reference claws with TEXT FK', () => {
    expect(migration).toMatch(/claw_id\s+TEXT/)
    expect(migration).toContain('REFERENCES claws(claw_id)')
    expect(migration).toContain('ON DELETE CASCADE')
  })

  it('should include status CHECK constraint with all values', () => {
    expect(migration).toContain("'pending'")
    expect(migration).toContain("'approved'")
    expect(migration).toContain("'rejected'")
    expect(migration).toContain("'expired'")
  })

  it('should default status to pending', () => {
    expect(migration).toContain("DEFAULT 'pending'")
  })

  it('should create index', () => {
    expect(migration).toContain('idx_drafts_claw_status')
  })

  it('should enable Row Level Security', () => {
    expect(migration).toContain('ENABLE ROW LEVEL SECURITY')
    expect(migration).toContain('drafts')
  })
})
